### ISSUE TITLE
Keeping track of which keys are down

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#226]
When I click some elements, I want something different to happen if I hold down shift or ctrl, for example. However, I can't figure out how to get the events of key presses and register save in the component state.

If I add onKeyUp trigger in the root panel of the view, like:

```
DockPanel.onKeyDown (fun e -> 
    printfn "Key Down %A" e.Key ;
    match e.Key with
    | Key.LeftShift -> keyPressState.Set { keyPressState.Current with LeftShiftDown = true }
    | Key.RightShift -> keyPressState.Set { keyPressState.Current with RightShiftDown = true }
    | Key.LeftCtrl -> keyPressState.Set { keyPressState.Current with LeftCtrlDown = true }
    | Key.RightCtrl -> keyPressState.Set { keyPressState.Current with RightCtrlDown = true }
    | Key.LeftAlt -> keyPressState.Set { keyPressState.Current with LeftAltDown = true }
    | Key.RightAlt -> keyPressState.Set { keyPressState.Current with RightAltDown = true }
    | _ -> ()
) ;
DockPanel.onKeyUp (fun e -> 
    printfn "Key Up %A" e.Key ;
    match e.Key with
    | Key.LeftShift -> keyPressState.Set { keyPressState.Current with LeftShiftDown = false }
    | Key.RightShift -> keyPressState.Set { keyPressState.Current with RightShiftDown = false }
    | Key.LeftCtrl -> keyPressState.Set { keyPressState.Current with LeftCtrlDown = false }
    | Key.RightCtrl -> keyPressState.Set { keyPressState.Current with RightCtrlDown = false }
    | Key.LeftAlt -> keyPressState.Set { keyPressState.Current with LeftAltDown = false }
    | Key.RightAlt -> keyPressState.Set { keyPressState.Current with RightAltDown = false }
    | _ -> ()
) ;
```
this does not get called when I press a key. However, if I add the same thing under the MainWindow class as
```
with member this.OnKeyDown (e : KeyEventArgs) =
            printfn "Key Down %A" e.Key ;
            ...
```
this does get called at every key-press, but the window class does not have access to the state, which lives in the components. 

Is there some way of doing this?

**Comment by sleepyfran** [comment]
I believe the problem you're facing is due to the fact that you didn't have the DockPanel focused. If you click on the panel, can you still repro this issue?

I just modified the ContactBook example to add a `onKeyDown` handler to the main DockPanel and it does not work initially, however once you click something inside of that panel (even if it's a blank space) it starts to work:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/6024783/199617908-4d58a135-ad63-4044-a1c6-5d544d2f5292.png">

Whether this should be the desired behavior or not is not up to FuncUI since we're just wrapping Avalonia's properties, so you can maybe raise this on the upstream repo if you'd like to discuss this.

One workaround that you can use if you need a global handler is to create a global store like the one we have in the ContactBook example: [Types.fs](https://github.com/fsprojects/Avalonia.FuncUI/blob/a0ca5bdd1fd288e46bc66c64774865a4051851bf/src/Examples/Component%20Examples/Examples.ContactBook/Types.fs#L34). With this in place you can call Set on the store inside the `OnKeyDown` handler in the MainWindow and then in your component do a `ctx.usePassedRead Store.shared.Keys` to retrieve the value.

**Comment by arnesahlberg** [comment]
Good tips. Thanks. 😊

tors 3 nov. 2022 kl. 00:01 skrev Fran González ***@***.***>:
