### ISSUE TITLE
Different naming for dotnet new funcui

### ISSUE THREAD

**Issue by MarkuBu** [fsprojects/Avalonia.FuncUI#236]
I noticed that there is an issue with the naming of funcui if you want to create a new project with dotnet new on the main page from the Wiki

https://github.com/fsprojects/Avalonia.FuncUI/wiki

The command for the basic template is correct

`dotnet new funcui.basic -n NewApp`

The naming for full is different. The Wiki says:

`dotnet new funcui.full -n NewApp`

The correct spelling is

`dotnet new funcUI.full -n NewApp`

quickstart doesn't seem to exist at all (sorry for the German)

```
~/dev/fsharp/avalonia$ dotnet new list funcui
Diese Vorlagen stimmen mit der Eingabe überein: 'funcui'

Vorlagenname                       Kurzname          Sprache  Tags                      
---------------------------------  ----------------  -------  --------------------------
Avalonia FuncUI App                funcui.basic.mvu  F#       Console/Avalonia/UI/Elmish
Avalonia FuncUI App                funcui.basic      F#       Console/Avalonia/UI/Elmish
Avalonia FuncUI App (with extras)  funcUI.full.mvu   F#       Console/Avalonia/UI/Elmish
Avalonia FuncUI App (with extras)  funcUI.full       F#       Console/Avalonia/UI/Elmish
```

**Comment by ShalokShalom** [comment]
I think they updated the templates. This is good, since the funcui.basic and funcUI.full examples seem to showcase the components model now. There had been no examples of that before. 

And in the process of this, seems the template for quickstart had been deleted.
I will commit a rudimentary update to the Wiki via pull request. 

Thanks for confirming, that I am not just overworked and sleep deprived, and this is really out of date. 😉
